config/routes.rb
Rails.application.routes.draw do

  
  resources :pokemons, only: [:index, :show, :destroy]
  resources :battles, only: [:show, :new, :create]
  resources :trainers, only: [:edit, :update, :show, :index]
  resources :moves
  resources :move_sets
  get "/attack", to: "battles#attack", as: "attack"
  get "/counterattack", to: "battles#counterattack", as: "counterattack"
  get "/", to: "static#home", as: "home"
end

app/models/battle.rb
class Battle < ApplicationRecord
    belongs_to :user, class_name: 'Pokemon'
    belongs_to :opponent, class_name: 'Pokemon'
    #validates_uniqueness_of :user_id, scope: :opponent_id
   
    validate :disallow_self_referential_pokemon

    def disallow_self_referential_pokemon
        if user_id == opponent_id
        errors.add(:opponent_id, 'cannot challenge same pokemon')
        end
    end


    def user_attack_first? #return true or false
        if self.user.speed >= self.opponent.speed
            return true
        else 
            return false
        end
    end

    def user_strong_against?
        if self.user.type.name == "Water" && self.opponent.type.name == "Fire" || self.user.type.name == "Water" && self.opponent.type.name == "Rock" || self.user.type.name == "Water" && self.opponent.type.name == "Ground"
            return true
        elsif self.user.type.name == "Normal"
            return false
        elsif self.user.type.name == "Fire" && self.opponent.type.name == "Grass" || self.user.type.name == "Fire" && self.opponent.type.name == "Ice" || self.user.type.name == "Fire" && self.opponent.type.name == "Bug" 
            return true
        elsif self.user.type.name == "Electric" && self.opponent.type.name == "Water" || self.user.type.name == "Electric" && self.opponent.type.name == "Flying"
            return true
        elsif self.user.type.name == "Grass" && self.opponent.type.name == "Water" || self.user.type.name == "Grass" && self.opponent.type.name == "Ground" ||self.user.type.name == "Grass" && self.opponent.type.name == "Rock"
            return true
        elsif self.user.type.name == "Ice" && self.opponent.type.name == "Grass"|| self.user.type.name == "Ice" && self.opponent.type.name == "Flying" 
            return true
        elsif self.user.type.name == "Fighting" && self.opponent.type.name ==  "Rock" || self.user.type.name == "Fighting" && self.opponent.type.name == "Normal" || self.user.type.name == "Fighting" && self.opponent.type.name == "Ice"
            return true
        elsif self.user.type.name == "Poison" && self.opponent.type.name == "Grass" ||self.user.type.name == "Poison" && self.opponent.type.name == "Bug"
            return true
        elsif self.user.type.name == "Ground" && self.opponent.type.name == "Fire" || self.user.type.name == "Ground" && self.opponent.type.name == "Electric" || self.user.type.name == "Ground" && self.opponent.type.name == "Poison" || self.user.type.name == "Ground" && self.opponent.type.name == "Rock"
            return true
        elsif self.user.type.name == "Flying" && self.opponent.type.name == "Bug" || self.user.type.name == "Flying" && self.opponent.type.name == "Grass" || self.user.type.name == "Flying" && self.opponent.type.name == "Fighting"
            return true
        elsif self.user.type.name == "Psychic" && self.opponent.type.name == "Fighting" || self.user.type.name == "Psychic" && self.opponent.type.name == "Poison"
            return true
        elsif self.user.type.name == "Bug" && self.opponent.type.name == "Grass" || self.user.type.name == "Bug" && self.opponent.type.name == "Poison" || self.user.type.name == "Bug" && self.opponent.type.name == "Psychic"
            return true
        elsif self.user.type.name == "Rock" && self.opponent.type.name == "Fire" || self.user.type.name == "Rock" && self.opponent.type.name == "Ice" || self.user.type.name == "Rock" && self.opponent.type.name == "Flying" || self.opponent.type.name == "Bug"
            return true
        else
            return false
        end     
    end

    def opponent_strong_against?
        if self.opponent.type.name == "Water" && self.user.type.name == "Fire" || self.opponent.type.name == "Water" && self.user.type.name == "Rock" || self.opponent.type.name == "Water" && self.user.type.name == "Ground"
            return true
        elsif self.opponent.type.name == "Normal"
            return false
        elsif self.opponent.type.name == "Fire" && self.user.type.name == "Grass" || self.opponent.type.name == "Fire" && self.user.type.name == "Ice" || self.opponent.type.name == "Fire" && self.user.type.name == "Bug" 
            return true
        elsif self.opponent.type.name == "Electric" && self.user.type.name == "Water" || self.opponent.type.name == "Electric" && self.user.type.name == "Flying"
            return true
        elsif self.opponent.type.name == "Grass" && self.user.type.name == "Water" || self.opponent.type.name == "Grass" && self.user.type.name == "Ground" || self.opponent.type.name == "Grass" && self.user.type.name == "Rock"
            return true
        elsif self.opponent.type.name == "Ice" && self.user.type.name == "Grass"|| self.opponent.type.name == "Ice" && self.user.type.name == "Flying" 
            return true
        elsif self.opponent.type.name == "Fighting" && self.user.type.name ==  "Rock" || self.opponent.type.name == "Fighting" && self.user.type.name == "Normal" || self.opponent.type.name == "Fighting" && self.user.type.name == "Ice"
            return true
        elsif self.opponent.type.name == "Poison" && self.user.type.name == "Grass" || self.opponent.type.name == "Poison" && self.user.type.name == "Bug"
            return true
        elsif self.opponent.type.name == "Ground" && self.user.type.name == "Fire" || self.opponent.type.name == "Ground" && self.user.type.name == "Electric" || self.opponent.type.name == "Ground" && self.user.type.name == "Poison" || self.opponent.type.name == "Ground" && self.user.type.name == "Rock"
            return true
        elsif self.opponent.type.name == "Flying" && self.user.type.name == "Bug" || self.opponent.type.name == "Flying" && self.user.type.name == "Grass" || self.opponent.type.name == "Flying" && self.user.type.name == "Fighting"
            return true
        elsif self.opponent.type.name == "Psychic" && self.user.type.name == "Fighting" || self.opponent.type.name == "Psychic" && self.user.type.name == "Poison"
            return true
        elsif self.opponent.type.name == "Bug" && self.user.type.name == "Grass" || self.opponent.type.name == "Bug" && self.user.type.name == "Poison" || self.opponent.type.name == "Bug" && self.user.type.name == "Psychic"
            return true
        elsif self.opponent.type.name == "Rock" && self.user.type.name == "Fire" || self.opponent.type.name == "Rock" && self.user.type.name == "Ice" || self.opponent.type.name == "Rock" && self.user.type.name == "Flying" ||self.opponent.type.name == "Rock" && self.user.type.name == "Bug"
            return true
        else 
            return false
        end     
    end

    def super_effective_attack
        if user_strong_against? == true
            self.user.attack * 2
        elsif opponent_strong_against? == true
            self.opponent.attack * 2
        end
    end

    def user_final_damage
        if user_strong_against? == true && self.opponent.defence >= super_effective_attack
            1
        elsif user_strong_against? == true && self.opponent.defence < super_effective_attack
            super_effective_attack - self.opponent.defence
        elsif self.opponent.defence >= self.user.attack
            1
        else
            self.user.attack - self.opponent.defence
        end
    end

    def opponent_final_damage
        if opponent_strong_against? == true && self.user.defence >= super_effective_attack
            1
        elsif opponent_strong_against? == true && self.user.defence < super_effective_attack
            super_effective_attack - self.user.defence
        elsif self.user.defence >= self.opponent.attack
            1
        else
            self.opponent.attack - self.user.defence
        end
    end

    def user_current_hp 
        self.user.hp -= opponent_final_damage
        self.user.faint?
        self.user.hp
    end

    def opponent_current_hp 
        self.opponent.hp -= user_final_damage 
        self.opponent.faint?
        self.opponent.hp
    end

    def attack_turn
        turn = 1

    end

    def user_poke_hp
        poke_hp = self.user.hp - (opponent_final_damage * attack_turn)

    end



    # def attack
    #      if user_attack_first? == true
    #         opponent_current_hp
    #      else
    #         user_current_hp
    #      end
    # end

    # def counterattack
    #     if user_attack_first? == true 
    #         user_current_hp
    #     else 
    #         opponent_current_hp
    #     end
    # end
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def show
    @battle = Battle.find(params[:id])
    render :show
  end
  
  def new
    @battle = Battle.new
  end

  def create
    @battle = Battle.new
    @battle.opponent = Pokemon.all.sample
    @battle = Battle.create(user_id: params["battle"]["user_id"], opponent_id: @battle.opponent.id)
    if @battle.valid?
      @battle.save
      redirect_to battle_path(@battle)
    else
      array_ids = Pokemon.all.map {|p| p.id}
      deleted_id = array_ids.delete(params["battle"]["user_id"].to_i)
      @battle.update(opponent_id: array_ids.sample)
      byebug
      redirect_to battle_path(@battle)
    end
  end

  def attack
    @battle = Battle.find(params[:format])
      if @battle.user_attack_first? 
         @defendant = @battle.opponent
         @attacker = @battle.user
         @battle.opponent_current_hp
      else
        @attacker = @battle.opponent
        @defendant = @battle.user
        @battle.user_current_hp
      end
      newhp = @defendant.hp
      @defendant.update_attributes(:hp => newhp)
    render :attack
  end

  def counterattack
    @battle = Battle.find(params[:format])
    if @battle.user_attack_first? 
      @defendant = @battle.user
      @attacker = @battle.opponent
      @battle.user_current_hp
   else
     @attacker = @battle.user
     @defendant = @battle.opponent
     @battle.opponent_current_hp
   end
   newhp = @defendant.hp
   @defendant.update_attributes(:hp => newhp)
    render :counterattack
  end

private
  def battle_params
    params.require(:battle).permit(:user_id, :opponent_id)
  end
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/views/battles/_arena.html.erb
<div class="arena_battle_image">
<img style="display: block; max-width: 200px;" src=https://www.pokemonbattlearena.net/members/theme/assets/IMG/pba_logo.png>
</div>


<h2 class="vs"> <%= @battle.user.species %> VS <%= @battle.opponent.species %> </h2> 
<div style="width:98%; margin:1%;">


<div class="ui container">
    <table class="center">
    <!-- <tr> 
        <td class="td"> <h3> <%= @battle.user.species %></h3> </td>
        <td class="td"> <h3> <%= @battle.opponent.species  %> </h3> </td>
    </tr> -->
    <tr>
        <td class="td"><h3> Type: <%= @battle.user.type.name %> </h3></td>
        <td class="td"><h3> Type: <%= @battle.opponent.type.name %> </h3></td>
    </tr>
    <tr>
        <td class="td"><h3> Speed: <%= @battle.user.speed %> </h3> </td>
        <td class="td"><h3> Speed: <%= @battle.opponent.speed %> </h3> </td>
    </tr>
    <tr>
        <td class="td"><h3> Health Points: <%= @battle.user.hp %></h3> <progress value="<%= @battle.user.hp %>" max="10"> </progress></td>
        <td class="td"><h3> Health Points: <%= @battle.opponent.hp %> </h3> <progress value="<%= @battle.opponent.hp %>" max="10"> </progress></td>
    </tr>
    <tr>
        <td class="td"><h3> Attack: <%= @battle.user.attack %> </h3> </td>
        <td class="td"><h3> Attack: <%= @battle.opponent.attack %> </h3> </td>
    </tr>
    <tr>
        <td class="td"><h3> Defence: <%= @battle.user.defence %> </h3> </td>
        <td class="td"><h3> Defence: <%= @battle.opponent.defence %> </h3>  </td>
    </tr>
    <tr>
        <td class="td"><img class=image src=<%= @battle.user.image %>> </td>
        <td class="td"><img class=image src=<%= @battle.opponent.image%>>  </td>
    </tr>
    </table>

</div>

</div>



<!-- table {
    border-spacing: 50px 0px;
    padding: 0px 150px;
} -->

app/views/battles/_gameover.html.erb
<h3 class="gameover"> GAME OVER 
<% if @battle.user.hp == 0  %>
<h3 class="gameover"><%= button_to "Start New Game", pokemon_path(@battle.user), method: :delete, class: "homebutton" %></h3>
<% else %>
<h3 class="gameover"><%= button_to "Start New Game", pokemon_path(@battle.opponent), method: :delete, class: "homebutton" %></h3>
<% end %>
</h3>

app/views/battles/attack.html.erb
<%= render partial: "arena" %>
<div class="attack" style="text-align: center; justify-content: center; font-size: 130%; line-height: 15pt; background-color: #ffcb05;">

<%= "#{@attacker.species} is attacking  #{@defendant.species}" %> 
<% if @attacker == @battle.user && @battle.user_strong_against? %>
    <%= "#{@attacker.species} is a #{@attacker.type.name} type and its attack is super effective against #{@defendant.type.name} types" %> <br>
    <%= "#{@attacker.species}'s power has doubled" %>
<% elsif @attacker == @battle.opponent && @battle.opponent_strong_against? %>
    <%= "#{@attacker.species} is a #{@attacker.type.name} type and its attack is super effective against #{@defendant.type.name} types" %> <br>
    <%= "#{@attacker.species}'s power has doubled" %>
<% end %><br>



<%= "#{@defendant.species} defended #{@defendant.defence} damage" %> <br>
<%= "#{@defendant.species} took" %>

<% if @defendant == @battle.user %>
    <%= "#{@battle.opponent_final_damage} damage" %>
<% else %>
    <%= "#{@battle.user_final_damage} damage" %>
<% end %> <br>

<%= "#{@defendant.species}'s health dropped down to #{@defendant.hp}" %> <br>
<br>
<% if @defendant.hp == 0 %>
    <%= "#{@attacker.species.upcase} WINS!" %>
    <%= render partial: "gameover" %>
<% else %>
    <%= button_to "Counterattack", counterattack_path(@battle), method: :get, class: "homebutton" %>
<% end %>

</div>


    

app/views/battles/counterattack.html.erb
<%= render partial: "arena" %>

<div class="attack" style="text-align: center; justify-content: center; font-size: 130%; line-height: 15pt; background-color: #ffcb05;">

<%= "#{@attacker.species} is attacking  #{@defendant.species}" %> 
<% if @attacker == @battle.user && @battle.user_strong_against? %>
    <%= "#{@attacker.species} is a #{@attacker.type.name} type and its attack is super effective against #{@defendant.type.name} types" %> <br>
    <%= "#{@attacker.species}'s power has doubled" %>
<% elsif @attacker == @battle.opponent && @battle.opponent_strong_against? %>
    <%= "#{@attacker.species} is a #{@attacker.type.name} type and its attack is super effective against #{@defendant.type.name} types" %> <br>
    <%= "#{@attacker.species}'s power has doubled" %>
<% end %><br>



<%= "#{@defendant.species} defended #{@defendant.defence} damage" %> <br>
<%= "#{@defendant.species} took" %>

<% if @defendant == @battle.user %>
    <%= "#{@battle.opponent_final_damage} damage" %>
<% else %>
    <%= "#{@battle.user_final_damage} damage" %>
<% end %> <br>

<%= "#{@defendant.species}'s health dropped down to #{@defendant.hp}" %> <br>
<br>
<% if @defendant.hp == 0 %>
    <%= "#{@attacker.species} WINS!" %>
    <%= render partial: "gameover" %>
<% else %>
<%= button_to "Next Attack", attack_path(@battle), method: :get, class: "homebutton" %>
<% end %>

</div>

app/views/battles/new.html.erb
<img style="float: right; padding: 30px 70px; vertical-align: top; width: 40%;" src="https://www.ssbwiki.com/images/thumb/2/21/Charizard_SSBU.png/1200px-Charizard_SSBU.png">


<div style="padding: 80px 100px 0 0; justify-content: center; text-align: center;">
            <h1 class="titles">New Battle</h1>
</div>
<div style="font-family: verdana; padding: 0 0; text-align: center;">
            <%= form_for @battle do |f| %>
            <%= f.label :user_id, "Pick your Pokémon" %> 
            <%= f.collection_select :user_id, Pokemon.all, :id, :species %>
            <%= f.submit "Start Battle", class: "homebutton" %>
            <% end %>
 
</div>
<br>


<br>

<img style="float: left; padding: 30px 50px; vertical-align: bottom; width: 30%;" src="https://cdn.bulbagarden.net/upload/7/73/002Ivysaur.png">

app/views/battles/show.html.erb
<%= render partial: "arena" %>


<h2 class="attack_button"><%= button_to "Attack", attack_path(@battle), method: :get, class: "homebutton" %></h2>