config/routes.rb
Rails.application.routes.draw do

  
  resources :pokemons, only: [:index, :show, :destroy]
  resources :battles, only: [:show, :new, :create]
  resources :trainers, only: [:edit, :update, :show, :index]
  resources :moves
  resources :move_sets
  get "/attack", to: "battles#attack", as: "attack"
  get "/counterattack", to: "battles#counterattack", as: "counterattack"
  get "/", to: "static#home", as: "home"
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    has_many :battles, class_name: "Pokemon", foreign_key: "user_id"
    has_many :battles, class_name: "Pokemon", foreign_key: "opponent_id"
    has_many :move_sets
    has_many :moves,  through: :move_sets
    belongs_to :trainer, optional: true

    validates :species, uniqueness: {case_sensitive: false}

    def faint?
        if self.hp <= 0 
            self.hp = 0
            return true
         else 
            return false
         end
    end
    def self.reset_health(pokemon) 
        
        pokemon.hp = rand(1..10)
        pokemon.save
    end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def index
    @pokemons = Pokemon.all
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end
  
  def destroy
    @pokemon = Pokemon.find(params[:id])
    Pokemon.reset_health(@pokemon)
    redirect_to home_path
  end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/index.html.erb
<h1 class="titles", style="padding: 20px 100px; justify-content: center; text-align: center;">All Pokémon</h1>

<div style="justify-content: center; padding: 20px 50px;">

<div class="ui grid">
    <% @pokemons.each do |p| %>
        <div class="two wide column"><h4><%=link_to p.species, pokemon_path(p), class: "link" %></h4><img style="display:block; width: 60%" src=<%= p.image%>></div>
  
    <% end %>
</div>

</div>
<br>
    <h3 style="padding: 0 110px; text-align: center;"><%= button_to "Homepage", home_path, method: :get, class: "homebutton" %></h3>

app/views/pokemons/show.html.erb
<img style="float: right; padding: 10px 100px; vertical-align: top; width: 50%;" src=<%= @pokemon.image %>>
<h1 class="titles" style="padding: 20px 100px; justify-content: center;"><%= @pokemon.species %></h1>

<div style="padding: 10px 100px;">


<h3> Type: <%= @pokemon.type.name %> </h3>
<h3> Speed: <%= @pokemon.speed %> </h3>
<h3> Health Points: <%= @pokemon.hp %> </h3>
<h3> Attack: <%= @pokemon.attack %> </h3>
<h3> Defence: <%= @pokemon.defence %> </h3> <br>
<br>


<h3><%= button_to "All Pokemon", pokemons_path, method: :get, class: "homebutton"%></h3>

</div>