config/routes.rb
Rails.application.routes.draw do

  
  resources :pokemons, only: [:index, :show, :destroy]
  resources :battles, only: [:show, :new, :create]
  resources :trainers, only: [:edit, :update, :show, :index]
  resources :moves
  resources :move_sets
  get "/attack", to: "battles#attack", as: "attack"
  get "/counterattack", to: "battles#counterattack", as: "counterattack"
  get "/", to: "static#home", as: "home"
end

app/models/trainer.rb
class Trainer < ApplicationRecord
    has_many :pokemons
    validates :name, uniqueness: {case_sensitive: false}
    validates :pokemons, length: { minimum: 0, maximum: 6 , message: "Allowed Per Team Is Maximum 6"}
end

app/controllers/trainers_controller.rb
class TrainersController < ApplicationController
    def edit
        @trainer = Trainer.find(params[:id])
    end

    def update
        @trainer = Trainer.find(params[:id])
        @trainer.update(trainer_params)
        if @trainer.valid? 
            @trainer.save
            redirect_to trainer_path(@trainer)
        else 
            render :edit
        end
    end
    
    def index
        @trainers = Trainer.all 
    end

    def show 
        @trainer = Trainer.find(params[:id])
    end

    def new
        @trainer = Trainer.new
    end

    def create
        @trainer = Trainer.create(trainer_params)
        if @trainer.valid?
            @trainer.save
            redirect_to trainer_path(@trainer)
        else
            render :new
        end
    end

    private 
    def trainer_params 
        params.require(:trainer).permit(:name, :image, :pokemon_ids => [])
    end
end

app/helpers/trainers_helper.rb
module TrainersHelper
end

app/views/trainers/edit.html.erb
<div style="padding: 20px 100px; justify-content: center;">

<h1 class="titles"> Team Builder for <%= @trainer.name.upcase %> </h1>
<h1> </h1>
<div class="ui form">
        <div class="ui form error">
        <div class="field">
            <% if @trainer.errors.any? %>
                <% @trainer.errors.full_messages.each do |message| %>
                    <div class="ui error message"><h5 style="color: red;"> <%= message %> </h5></div>
                <% end %> 
            <% end %>
            </div>
        </div>
        </br>
    <%= form_for @trainer do |f| %>
        <div class="fields">
            <h4><%= f.label :pokemons,  "Pick up to 6 Pokémon for your team:" %></h4>
            <div class="field">
                    <h4><%= f.collection_check_boxes :pokemon_ids, Pokemon.all, :id, :species %></h4> 
            </div>
        </div>
     
        <h4><%= f.submit "Catch Pokémon", class: "homebutton" %></h4> <br>
    <% end %> <br>

</div>
<br>
<h1> </h1>
<br>
<div class="ui grid">
    <% Pokemon.all.each do |p| %>
        <div class="two wide column"><img style="display:block; width: 60%" src=<%= p.image%>></div>
    <% end %>
</div>

</div>

app/views/trainers/index.html.erb
<div style="justify-content: center; padding: 20px 50px;">
<h1 class="titles" style="text-align: center;"> All Trainers </h1> 
<h4 style="text-align: center;"><%= button_to "Homepage", home_path, method: :get, class: "homebutton" %></h4>
<h4 style="text-align: center;"><%= button_to "Create New Trainer", new_trainer_path, method: :get, class: "homebutton" %></h4>
</div>

<div style="justify-content: center; padding: 50px 50px;">

<div class="ui grid">
        <% @trainers.each do |t| %>       
        <div class="two wide column"> <h4 class="link"><%= link_to t.name, trainer_path(t) %></h4> <img style="justify-content: center; align-items: center; display:block; object-fit: contain; width: 70%; height: 50%;" src=<%= t.image%> </div>
        </div>
        <%end %>
</div>
</div>
</div>

app/views/trainers/new.html.erb
<div style="padding: 50px 100px; justify-content: center; text-align: center;">

        <h1 class="titles"> Create New Trainer </h1>

                    <% if @trainer.errors.any? %>
                        <% @trainer.errors.full_messages.each do |message| %>
                            <div class="ui error message"><h5 style="color: red;"> <%= message %> </h5></div>
                        <% end %> 
                    <% end %>
       
                </br>


<div class="ui form" style="justify-content: center; text-align: center; padding: 100px, margin: auto;">

<%= form_for @trainer do |f| %>
    <div class="field">
        <%= f.label :name %>
        <%= f.text_field :name %>
   </div>
   <div class="field">
        <%= f.label :image %>
        <%= f.text_field :image %> <br>
   </div>
    <%= f.submit "Create Trainer", class: "homebutton"%>
    <% end %>

</form>

<img style="float: bottom; padding: 30px 70px; vertical-align: bottom; horizontal-align: center; width: 65%;" src="https://slack-imgs.com/?c=1&o1=ro&url=https%3A%2F%2Fimages-wixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F8bcbac46-c322-4678-9738-e08774e90a1e%2Fddatef3-6b70f60f-7d1c-49de-8841-b12d133251a9.png%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOiIsImlzcyI6InVybjphcHA6Iiwib2JqIjpbW3sicGF0aCI6IlwvZlwvOGJjYmFjNDYtYzMyMi00Njc4LTk3MzgtZTA4Nzc0ZTkwYTFlXC9kZGF0ZWYzLTZiNzBmNjBmLTdkMWMtNDlkZS04ODQxLWIxMmQxMzMyNTFhOS5wbmcifV1dLCJhdWQiOlsidXJuOnNlcnZpY2U6ZmlsZS5kb3dubG9hZCJdfQ.uqxhXKNLa2r-0SQhO4-x2eE6eieUQxIFt0Ra9GExfNg">

app/views/trainers/show.html.erb
<img style="float: right; padding: 10px 100px; vertical-align: top; width: 50%;" src=<%=@trainer.image%>>

<h1 class="titles" style="padding: 20px 50px; justify-content: center;"> <%= @trainer.name %>'s Team </h1>
<div style="padding: 10px 50px;">

<div class="ui grid">
<% @trainer.pokemons.each do |p| %>
  <div class="four wide column"><h4 class="link"><%= link_to p.species, pokemon_path(p)%></h4><img style="display:block; width: 80%" src=<%= p.image%>></div>
<% end %>
</div>

</div>
<br>
    <h3 style="padding: 0 50px;"><%= button_to "Build Team", edit_trainer_path(@trainer), method: :get, class: "homebutton" %></h3>
    <h3 style="padding: 0 50px;"><%= button_to "All Trainers", trainers_path, method: :get, class: "homebutton" %></h3>
    <h3 style="padding: 0 50px;"><%= button_to "Homepage", home_path, method: :get, class: "homebutton" %></h3>